### ISSUE TITLE
[Feat] 피날레프로젝트 게시글 CRUD API 개발

### ISSUE THREAD

**Issue by zyu22** [zyu22/honeyboard-server#20]
# 피날레 프로젝트 팀 게시글 CRUD API 구현

## **주의 사항**
- 노션에 있는 API명세서 확인 후 API 작성해주세요.
- DTO 명은 변경 가능합니다. 다만 변경 됐으면 이슈 댓글에 입력해주세요.

## **📋 이슈 요약**
> 개발할 API의 핵심 내용을 간략히 설명해주세요.
- **피날레 프로젝트 게시글 전체 조회** (`GET /api/v1/project/finale/{finaleId}/board`) 구현
- **피날레 프로젝트 게시글 상세 조회** (`GET /api/v1/project/finale/{finaleId}/board/{boardId}`) 구현
- **피날레 프로젝트 게시글 작성** (`POST /api/v1/project/finale/{finaleId}/board`) 구현
- **피날레 프로젝트 게시글 수정** (`PUT /api/v1/project/finale/{finaleId}/board/{boardId}`) 구현
- **피날레 프로젝트 게시글 삭제** (`DELETE /api/v1/project/finale/{finaleId}/board/{boardId}`) 구현

## **📝 작업 내용**
> API를 개발하기 위해 진행해야 할 세부 작업을 작성해주세요.

### **1) DTO (Data Transfer Object) 작성**
- `FinaleProjectBoard`: 게시글 작성/수정을 위한 DTO
-
### **2) Service 계층 구현**
- FinaleProjectBoardService
  - `getAllBoard(int finaleId)`: 게시글 전체 조회
  - `getBoard(int boardId)`: 게시글 상세 조회
  - `addBoard(int finaleId, FinaleProjectBoard board)`: 게시글 작성
  - `updateBoard(int boardId, FinaleProjectBoardboard)`: 게시글 수정
  - `softDeleteBoard(int boardId)`: 게시글 삭제

### **3) Controller 계층 구현**
- **게시글 전체 조회 API**: 페이징 처리된 게시글 목록 조회
- **게시글 상세 조회 API**: 게시글 상세 정보 조회
- **게시글 작성 API**: 새로운 게시글 작성
- **게시글 수정 API**: 게시글 수정
- **게시글 삭제 API**: 게시글 삭제

## **✅ 체크리스트**
> API 개발을 완료하기 위해 필요한 작업을 체크리스트로 작성하세요.
- [x] **DTO 작성**
  - [x] DTO: `FinaleProjectBoard`

- [ ] **Service 구현**
  - [ ] getAllBoard(): 전체 조회
  - [ ] getBoard(): 상세 조회
  - [ ] addBoard(): 작성
  - [ ] updateBoard(): 수정
  - [ ] softDeleteBoard(): 삭제

- [ ] **Controller 구현**
  - [ ] 전체 조회 API (페이징)
  - [ ] 상세 조회 API
  - [ ] 작성 API
  - [ ] 수정 API
  - [ ] 삭제 API

## **📌 기능 요구사항**
> API의 구체적인 동작과 요구사항을 명확히 작성해주세요.

### **정상 동작**
- 페이징 처리된 게시글 목록 조회
- 게시글 상세 정보 조회
- 새로운 게시글 작성
  - 팀 프로젝트 업데이트 날짜 갱신
- 게시글 내용 수정
- 게시글 삭제 처리

### **유효성 검사**
- finaleId, boardId 존재 여부 확인
- 게시글 작성/수정 시 필수 입력값 검증
- 작성자 본인 확인
- 제출 가능 여부 확인

### **에러 처리**
- 필수값 누락: `400 Bad Request`
- 존재하지 않는 게시글: `204 NO_CONTENT`
- 서버 오류: `500 Internal Server Error`
- 권한 없음: `401 UNAUTHORIZED`

## **💬 고려사항**
> 특별히 신경써야 할 부분이나 추가 논의가 필요한 부분을 작성해주세요.
- **권한**: 게시글 작성/수정/삭제 권한 체크
- **동시성**: 제출 처리 시 동시성 제어
- **확장성**: 추가 게시글 상태 확장 고려
- **유효성**: 게시글 데이터 검증

## **🔗 참고 자료**
> 개발에 도움이 될 레퍼런스를 공유해주세요.

**Comment by rpeowiqu** [comment]
가져갑니다~
