### ISSUE TITLE
[Feat] 이미지 업로드 API 개발

### ISSUE THREAD

**Issue by zyu22** [zyu22/honeyboard-server#34]
## **📋 이슈 요약**  
> 이미지 업로드 API(`POST /api/v1/upload/image/{category}`) 구현
- Toast UI 에디터에서 사용할 이미지 업로드 API 개발

---

#### **1) DTO 작성**  
- `ImageUploadResponse`: S3 URL을 반환하기 위한 응답 객체 필요
 (단순 String 반환도 가능하나, 향후 확장성을 고려하여 DTO 사용 추천)

#### **2) Service 계층 구현**  
- S3Service
 - S3 업로드 로직 구현
 - 파일명 생성 로직(UUID + 원본파일명)
 - 카테고리별 경로 설정

#### **3) Controller 계층 구현**  
- `ImageController`
 - multipart/form-data 처리
 - 이미지 파일 유효성 검사
 - S3Service 호출

---

## **✅ 체크리스트**  
- [x] **S3 설정**
 - [x] AWS S3 bucket 접근 설정
 - [x] application.yml에 S3 설정 추가
- [x] **이미지 업로드 구현**
 - [x] 파일 용량 제한 설정
 - [x] 허용할 이미지 형식 정의
 - [ ] 카테고리별 저장 경로 설계
- [ ] **보안 설정**
 - [ ] 인증 필터 설정
 - [ ] CORS 설정

---

## **📌 기능 요구사항**  
- **정상 동작**:  
 - 이미지 파일을 S3에 업로드하고 URL 반환
 - 카테고리별로 다른 경로에 저장
- **유효성 검사**:  
 - 허용된 이미지 형식만 업로드 가능
 - 최대 파일 크기 제한
- **에러 처리**:  
 - 파일 누락: `400 Bad Request`
 - 인증 실패: `401 Unauthorized`
 - 파일 크기 초과: `413 Payload Too Large`
 - 서버 에러: `500 Internal Server Error`

---

## **💬 고려사항**  
- **성능**: 대용량 이미지 처리 방안 고려
- **보안**: 
 - 인증된 사용자만 업로드 가능
 - 안전한 파일 확장자 검증
- **저장소**: 
 - S3 저장소 관리 전략
 - 미사용 이미지 정리 방안
- **카테고리**: 
 - algorithm-guide
 - web-guide 등 카테고리 정의 필요

---

## **🔗 참고 자료**  
- AWS S3 문서: [링크]
- Spring Multipart 설정: [링크]
- Toast UI 에디터 문서: [링크]

**Comment by clapsheep** [comment]
ㅋㅋㅋㅋ아니 유림님 이거 다 클로드가 써주는거에요?! 참고자료 링크 뭐에요 눌러봤는데 아무것도 안됌
